///Backage Name Splash
package com.example.splash;///...
/////...
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import androidx.appcompat.app.AppCompatActivity;///...
////class name
public class contactus extends AppCompatActivity {
///variable name is hayat
Button hayatt;///
////...
@Override////
////...
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);///...//
setContentView(R.layout.activity_contactus);///..
///set of button
hayatt=(Button) findViewById(R.id.contact_us);///..
hayatt.setOnClickListener(new View.OnClickListener() {
@Override///....
public void onClick(View v) {
////Name of object is hayat... this code is to go back to home after
    /// show this current page
Intent hayat=new Intent(getApplication(),HomeActivity.class);///...
startActivity(hayat);////...
}///..
});///...
}///...
}///...