///The packagee include name of splash
package com.example.splash;
///codes to import the context///
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;

import androidx.appcompat.app.AppCompatActivity;
////codes to extends the splash activity
public class MainActivity extends AppCompatActivity {
    Handler hayat;////variable of handler
    @Override///...
    protected void onCreate(Bundle savedInstanceState) {
///...
        super.onCreate(savedInstanceState);///..
///...
        setContentView(R.layout.activity_main);///...
        ////....
        hayat=new Handler();//Name of handler
        hayat.postDelayed(new Runnable() {
            ///...
            @Override////....
            public void run() {
                Intent i=new////...Name of the object is i
///codes to display splash page then login page
                        Intent(MainActivity.this,login.class);///...
                startActivity(i);///start with splash page
                finish();///f
            }
///period to display splash screen
        },4590);///...
    }///...
}///...